name: Build And Upload To S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # AWS Cofigure
      - name: Set AWS Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # S3へアップロード
      - name: Upload to S3
        run: |
          aws s3 sync public s3://${{ secrets.UPLOAD_S3_BUCKET }} --delete
